### ISSUE TITLE
Multiple Quick TapHold Issue

### ISSUE THREAD

**Issue by scottrosenquist** [david-janssen/kmonad#16]
I am currently having an issue while pressing multiple TapHold keys in quick succession. When I tap two TapHold keys one after the other as fast as I can, only the first one will register. If I tap one TapHold key and one regular key one after the other as fast as I can, both register.

**Comment by david-janssen** [comment]
Hmmm, interesting. I guess the moment a second tap-hold is pressed the first tap-hold should switch to 'held' status. I'll have a look at what is going on and let you know what I find.

**Comment by scottrosenquist** [comment]
>I guess the moment a second tap-hold is pressed the first tap-hold should switch to 'held' status.
 I don't think so. In this instance I am trying to get two tap actions, not a hold and tap.

 >but by that time the 2nd taphold is no longer starting to process during its own button push
I don't think this is entirely true either. I have successfully been able to use two tap hold modifiers together, as long as I am not going super quickly.

**Comment by scottrosenquist** [comment]
Oops...just manged to submit a work in progress comment and close the issue while attempting to test some key combos...

**Comment by scottrosenquist** [comment]
As I was saying, I was able to execute a shift + meta + 5 hotkey, shift and meta being tap holds for n and i, and 5 being a layer change, so some of it is working just fine.

I can share my config if you think that might help.

I'm dying to dive into this project, but my haskell skills are non existant and my time is not super free right now, but I am more than willing to test.

**Comment by david-janssen** [comment]
> I don't think so. In this instance I am trying to get two tap actions, not a hold and tap.

Yeah, that was my mistake. Got confused with a 'TapNext' button. 

> I don't think this is entirely true either. I have successfully been able to use two tap hold modifiers together, as long as I am not going super quickly.

Actually, this is true. So what happens, in more detail, is this:
- When a taphold is initially pressed, it requests  KMonad to send it messages about future key-presses as compared against the current key event.
- When the second taphold is pressed, its processing only starts after the first one has been released.
- By that time, however, the 'current key-event' is the release of the first button.

So now the second taphold is comparing future events against the release of the first taphold, instead of the press of itself.

This is reflected in the fact that, if you use `evtest` to inspect the output of the KMonad simulated keyboard, if you tap 2 TapHold buttons very quickly, the first will register as a press, the second will register as a 'Held' *even if you tapped it very quickly*. This is because the 2nd taphold is comparing against the release of the 1st taphold instead of vs it's own press. (This is just straight-up a bug/design issue). Once the timer expires, the 2nd taphold simply turns into its 'held' status (which in your case is a modifier).

As long as you release the first taphold before pressing the second, everything works as expected, but if you are typing quickly, and interleave the presses and releases, the second taphold will only be able to activate its 'held' status.

**Comment by scottrosenquist** [comment]
Ah, okay, I see. (Sort of... it's very complex.)

At some point I'll move from using the release binaries to the git repo so I can start testing stuff coming down the pipe.

I've recently gotten hooked on using an ergodox ez (borrowed from a friend) configured as a minidox, with colemak on top of that, and was concerned about laptop keyboards and my mistel barocco becoming effectively useless to me, and then I found this project. I look forward to further progress on this project, and will test as much as I can. If I have time, I might start perusing the source code.

I'm absolutely floored by how well this already works. Basically anything can have QMK now. Well done.

**Comment by scottrosenquist** [comment]
Oh, also, additionally, I have to assume this is a side effect of this bug, so I'm not going to make a separate issue, but occasionally the second TapHold will get stuck in the held position, until it is then held and released manually. Something to look out for for the refactor.

**Comment by david-janssen** [comment]
Thanks for the praise and the second headsup.

I made some good progress on the refactor (in the refactor branch). I honestly think this will probably be sorted in a couple of days. Will keep you up to date.

**Comment by david-janssen** [comment]
Just to let you know: the core issue you filed has been resolved in the 'refactor' branch. I will keep working on some other things related to this refactor. Then I have to make sure this runs on Windows too, at which point I will merge into master and update the binary. 

If you are on Linux and are willing to try compiling, you can give the refactor branch a shot and let me know. I've been running my own keyboard on it for a couple of hours now without issue.

**Comment by scottrosenquist** [comment]
Hey, I do use Linux! I got the project checked out, got Stack working, and fired up the refactor branch, and it works great!

I have noticed very minor and infrequent corner cases, where at the very fastest, I will still get the second tap hold modifier showing up (I'm using xev to see which keys are being reported to the OS), but during normal typing it seems to never come up. During these testing scenarios I have also been able to get the modifiers in the stuck position, but again, very rarely. I can only get it to happen when I deliberately attempt to trigger the bug. (It comes up the occasional time during regular typing, and 99% of the scenarios it does is trying to type a capital I. Thanks Colemak.)

**Comment by scottrosenquist** [comment]
Hey David, I haven't fiddled with this for a while. I'm currently on 1c4db8ccc5c9b00c6e427d59c2ba69594e38ed3a. It's been working fine with only the occasional hiccups which I already mentioned above. Very usable.

I see the refactor branch has come a long way. Do you have a commit that you'd recommend I jump in on? Or just go for the latest and see what happens?

**Comment by david-janssen** [comment]
Hey Scott,

Yeah, refactor has come a *long* way. The core engine has been completely redesigned from scratch, and I think there are currently 0 hiccups (brave words for untested software :-P). There is a big issue with the refactor branch at the moment, however: no parsers. There is simply no configuration language or documentation. If you are comfortable with Haskell you can probably write your own module where you specify a working config that does quite well, but there is no support.

Working on the parsers and config language is the next step, and I hope to have something up and running in a week or two. Check back then? :-)

Cheerio

**Comment by scottrosenquist** [comment]
David, wanted to let you know I have hopped on 673da311472e20abe083244433bb250d567e79da and it seems to be so far so good. I'll file any issues I find.

I'm glad I waited. Haskell is not my forte, and while I can sometimes discern from the source what is going on, I don't think I could write much.

That being said, if I found something I wanted to add/contribute to the Refactor branch, would that be welcome, or would that be a nuisance to juggle with what you're working on currently?

**Comment by david-janssen** [comment]
Oh wow, that's great! I was planning on writing some documentation and updating all of the syntax guides and releasing somewhere next week, but you've shown initiative! Try the '-v' flag to see detailed debug output of exactly what KMonad is doing, I'm quite proud of that one :-).

I think the core redesign has actually removed lots of tiny little race conditions that existed in KMonad before, so it should be a lot more solid. Let me know about anything you encounter, because at the moment there are still 2 or 3 features that I want to add, then there is the documentation and initial release phase, and finally it's bug-fixing and support, so any bug you find now will put us ahead of the curve.

And in regards to you wanting to contribute/add, that would be extremely welcome. Even if it is 'newbieish' code, I'd be happy to look it over and refactor it and give you some pointers. Haskell is a great language, and I'd be happy to shepherd people in its direction.

**Comment by david-janssen** [comment]
Closing this issue because I think it is solved now... Feel free to object and we can reopen.

**Comment by scottrosenquist** [comment]
Hey, yes, this has been resolved since I started using the refactor branch way back when, but I didn't close it because it wasn't as easily accessible yet and I wanted this to have some visibility for new users.

Thanks for all the work you've done on this, and glad to see you're doing better. (I think you weren't feeling well a bit back.) Anytime I have to use my laptop as a laptop, I am thankful for this project.
