### ISSUE TITLE
defunct procceses owned by kmonad when I run cmd-buttons

### ISSUE THREAD

**Issue by recallthis** [david-janssen/kmonad#211]
When I use cmd-button I seem to get defunct processes added to my ps list.

For example, setting cmd-button to run xinput and pressing the key will add a [xinput] defunct entry to my process list. Tutorial.kbd gives "[sh] defunct" entry.

Tested this in a miminal config and tried two kmonad versions. I've never seen defunct proccesses before so I'm not sure if I've done something wrong. Killing kmonad removes all the defunct processes from the ps list.

**Comment by slotThe** [comment]
This is, I think, related to us not spawning the process in a new session.  The process is marked as `defunct` because, while it completed successfully, we (as the parent process) are still watching it and hence it doesn't get cleaned up.

I have created #212 which should fix this; @recallthis care to give it a try?

**Comment by recallthis** [comment]
Hi, sure. Tested with my clean config but I'm still getting the same issue here.

In case I made an error (git novice), I downloaded from your github* page, did git checkout -b new-session, checked if the changes were applied to source then compiled with stack install, and ran ./kmonad from the build directory. 

\* https://github.com/slotThe/kmonad/tree/new-session.

**Comment by slotThe** [comment]
If the changes are there then you did the correct thing!

But you are quite right that it doesn't yet work; I must have messed the defunct processes.  What we _really_ have to do is to simply tell everyone that our child processes can be reaped and we are not watching them by ignoring `SIGCHLD`.  Can you perhaps try again with these new changes?

**Comment by recallthis** [comment]
Great stuff, seems to work in both of my configs. :)

**Comment by slotThe** [comment]
Great to hear!  Now we just need to figure out how to incorporate this (nicely; I'm hoping for no `CPP` here) into kmonad such that things don't break on systems other than GNU/Linux (which presumably happens right now with this patch).

**Comment by recallthis** [comment]
Sure. I'm not a programmer but let me know if you want me to test.
